In [83]:
import numpy as np

In [84]:
#1.define matrix A with size 3x5

In [105]:
a=np.array([0.46,0.67,0.76,0.18,0.99,0.70,0.72,0.83,0.07,0.76,0.01,0.15,0.61,0.57,0.07])

In [106]:
A = a.reshape(3,5)

In [107]:
print(A)

[[ 0.46  0.67  0.76  0.18  0.99]
 [ 0.7   0.72  0.83  0.07  0.76]
 [ 0.01  0.15  0.61  0.57  0.07]]


In [108]:
#2.compute exepnental function of each element

In [111]:
eA=np.array(A)

In [112]:
print(eA)

[[ 0.46  0.67  0.76  0.18  0.99]
 [ 0.7   0.72  0.83  0.07  0.76]
 [ 0.01  0.15  0.61  0.57  0.07]]


In [113]:
#3.Compute	summation	and	average	over	all	elements

In [115]:
aveA = np.average(A)

In [116]:
print(aveA)

0.503333333333


In [117]:
#4.Compute	average	of	each	row	or	each	columns

In [118]:
rowAveA = np.average(A,axis =0)

In [121]:
coluAveA = np.average(A,axis = 1)

In [122]:
print(rowAveA,coluAveA)

[ 0.39        0.51333333  0.73333333  0.27333333  0.60666667] [ 0.612  0.616  0.282]


In [123]:
#5.Compute	minimum	of	each	row	or	each	columns.

In [131]:
np.min(A,axis = 0)

array([ 0.01,  0.15,  0.61,  0.07,  0.07])