In [1]:
import numpy as np

In [ ]:
#1. Define	vector	xand	matrixY

In [8]:
x = np.array([[1],[3],[5],[7]])

In [9]:
x

array([[1],
       [3],
       [5],
       [7]])

In [10]:
y = np.array([[1,3,5,7],[9,11,13,15]])

In [11]:
y

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [12]:
#2. Compute	inner	product	xTx.

In [14]:
xt = x.Ｔ

In [15]:
xt

array([[1, 3, 5, 7]])

In [18]:
np.dot(xt,x)

array([[84]])

In [19]:
#3. Compute	product	Yx

In [20]:
np.dot(y,x)

array([[ 84],
       [212]])